name: Release Packages

on:
  push:
    tags:
      - 'build-releases-[0-9]+'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-packages:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Install Dependences
        run: npm ci
      
      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}
          TURBO_TOKEN: ${{ secrets.VERCEL_SECRET }}
          TURBO_TEAM: bsafer-ti
